name: flutter_keep
description: Projeto em Flutter para P2

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  flutter_launcher_icons: ^0.8.0
  flutter_launcher_name: ^0.0.1

  # Firebase
  firebase_core: ^0.4.4
  firebase_analytics: ^5.0.11
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.3
  google_sign_in: ^4.1.4

  collection_ext: ^0.2.0
  provider: ^4.0.2
  tuple: ^1.0.3
  intl: ^0.16.1
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true

  assets:
  - assets/images/

  fonts:
    - family: app-icons
      fonts:
        - asset: assets/fonts/app-icons.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_launcher_name:
  name: "FlutterKeep"
